# Exported from Render on 2024-07-29T23:28:33Z
services:
- type: web
  name: Registro_Tickets
  runtime: python
  repo: https://github.com/JCVLionHearth/Tickets
  plan: starter
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  disk:
    name: disk
    mountPath: /var/data
    sizeGB: 1
  autoDeploy: false
version: "1"
